### ISSUE TITLE
。。。。。。。。。。。。。

### ISSUE THREAD

**Issue by hyccgit** [weepsafe/BackupScanner#3]
![image](https://user-images.githubusercontent.com/24220639/121281617-c496b880-c90a-11eb-8528-a089bd75e113.png)
不懂

**Comment by weepsafe** [comment]
> ![image](https://user-images.githubusercontent.com/24220639/121281617-c496b880-c90a-11eb-8528-a089bd75e113.png)
> 不懂

我把exe混淆了一下，文件本身无任何敏感操作，你可以丢到微步里去看看

**Comment by weepsafe** [comment]
下个版本会发一个未混淆的原始exe文件

**Comment by hyccgit** [comment]
ok，感谢大佬的工具
